### ISSUE TITLE
NXInspired's Roadmap

### ISSUE THREAD

**Issue by mctaylors** [mctaylors/NXInspired#1]
**You can also suggest features by leaving a comment on this issue.**

### High priority:
- [x] Make a basic implementation of an error page
- [x] Make some button CSS animations
- [x] Add UI sounds
- [x] Make an appearance animation
- [x] Add second button support
  - [x] Add "details" screen
- [x] Make dialog height "dynamic"

### Medium priority:
- [x] Make bluish background blur
- [x] Add screen switching animation
- [x] Add "black screen of death"
 
### Low priority:
- [x] NXInspired's branding
 
### Planned:
- Add "software error" screen
  - **Note:** This screen has several variations and icons, it will be much more complicated to deal with than the original project idea.
- Add selection support with arrow keys
  - **Note:** This can be problematic because you have to be aware of possibility of the “double selection” bug, when using the mouse and keyboard at the same time
  - Add selection support with controller because why not
- Hard fork with PHP rewrite?
- ~~Get sued by Nintendo~~

**Comment by mctaylors** [comment]
> - Add selection support with arrow keys 
>   - **Note:** This can be problematic because you have to be aware of possibility of the “double selection” bug, when using the mouse and keyboard at the same time

However... (https://github.com/mctaylors/NXInspired/commit/95aea191c25fbcba186a39dc313e39622aa6c9ae related)

![image](https://github.com/mctaylors/NXInspired/assets/95250141/2799ccc2-f199-41b6-bf92-fb288e2099cc)

This commit also kills the button's post-animation (that just removes border) once clicked, but who needs it anyway? (Mostly) Every button will call the `close_button()` function, which loads another web page.
